apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbnextgh-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: fbnext-app
  template:
    metadata:
      labels:
        app: fbnext-app
    spec:
      containers:
        - name: fbnext-container
          image: ghcr.io/idjohnson/nodesite:main
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fbnextgh-service
spec:
  selector:
    app: fbnext-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP